### ISSUE TITLE
Error characters

### ISSUE THREAD

**Issue by odenisnobre** [SCADA-LTS/Scada-LTS#2502] opened 2023-04-05 10:58 UTC
How to get around the character problem in an email alert message?

![image](https://user-images.githubusercontent.com/8119694/230061023-48a7d795-61cd-4b57-9317-f2d10b9e45a9.png)

**Comment by Limraj** [comment] 2023-04-05 14:33
Hi @odenisnobre,
what version are you using?

Regards,
Kamil Jarmusik

**Comment by odenisnobre** [comment] 2023-04-05 14:44
Version 2.7.5.1

**Comment by Limraj** [comment] 2023-04-05 14:45
Can you provide the configuration of this alert? 
There may be a short description of what objects are affected, eventhandler, eventdetector? The point is so that I can reproduce your configuration and see the error. The source of the emails may vary.

**Comment by odenisnobre** [comment] 2023-04-05 15:08
I had to restart Scada-LTS and when I went back to get the settings I came across this error

![image](https://user-images.githubusercontent.com/8119694/230123565-42b8bcf7-540f-4803-bfd4-bda0732bccec.png)

**Comment by Limraj** [comment] 2023-04-05 15:20
Do you have a database server running?

1. I created a hadler for the system start event and I see no errors:
![email_noerror_3](https://user-images.githubusercontent.com/35842300/230126381-8b655470-dc23-46d6-9196-f7f9b6978b27.png)

And result:
![email_noerror_2](https://user-images.githubusercontent.com/35842300/230125391-57255c5f-30b4-41d5-9815-9a43b8c5381f.png)

2. I created a hadler for the envet detector:
![email_noerror_4](https://user-images.githubusercontent.com/35842300/230126413-4887d63f-3f7d-433e-a738-72c2d1cfa824.png)

And result:
![email_noerror](https://user-images.githubusercontent.com/35842300/230124461-99c0cc45-68f6-442c-8565-12773e05520c.png)

3. You probably have the wrong version installed, can you take a screenshot of the app:
![email_noerror_5](https://user-images.githubusercontent.com/35842300/230126970-472bb05e-c9d7-444f-bd66-bc8163b27ec2.png)


From version v2.7.4.1 there should be no such problems.

**Comment by odenisnobre** [comment] 2023-04-05 15:30
I updated my docker compose here and I'm going to test it again.
the behavior is not very nice but I'll check here.
volume mapping is not working, but I'll check here

**Comment by Limraj** [comment] 2023-04-05 15:33
@odenisnobre Don't make too hasty conclusions, if you have a problem, something doesn't work, try to describe it in such detail so that someone can reproduce it, then we will be able to help. The problem has not occurred since version 2.7.4.1 so you must have something old.

**Comment by odenisnobre** [comment] 2023-04-05 15:41
Alright, let's go.

Firstly, the email error, this was happening until I updated the containers.
I thought updating might fix it.
But after updating volume mapping is working properly.

![image](https://user-images.githubusercontent.com/8119694/230132528-41ce12aa-612c-4a86-9108-c131fce1e3de.png)

![image](https://user-images.githubusercontent.com/8119694/230132620-7d7a5f73-e6cb-43fb-b054-16e3bbe502c0.png)

**Comment by Limraj** [comment] 2023-04-05 15:52
@odenisnobre, So it's working okay?

If you had a version before 2.7.4.1, this error was present, after this version, it should no longer occur, I showed you on the screenshots that it does not occur, although it is not proof that it does not occur from version 2.7.4.1, but from this version, we did not deal with this issue, and there is probably no point in checking each subsequent version, since it works in the current one. 

I also checked on version 2.7.5.1:
![email_noerror_7](https://user-images.githubusercontent.com/35842300/230135444-1f0dc37e-0ed7-422e-8292-af67215fd0fd.png)

and result:
![email_noerror_6](https://user-images.githubusercontent.com/35842300/230135438-39ad7127-c875-47d5-8863-f65a1a86710d.png)

Try not to keep two folders with the application in webapps.

**Comment by odenisnobre** [comment] 2023-04-05 15:55
All good.
I believe that when emails should work.
Now talking about the docker volume, inside the webapps folders does it have to be the Scada-LTS folder, only?

**Comment by Limraj** [comment] 2023-04-05 16:02
@odenisnobre 
Theoretically it can be any name, tomcat will load the application which will be available under the name of the folder. Some parts of the system may even refer to the older ScadaBR. However, in the basic functions of the application, this is not a problem.

Running two applications on one volume means, for example, 2x the pool of connections to the database, i.e. 2x more connections. Besides, theoretically there should be no conflicts, nothing comes to mind right now. However, if it is not necessary, it is better not to keep two applications in webapps, if only because of these database connections.

**Comment by odenisnobre** [comment] 2023-04-05 16:03
OK.

So can I just leave a Scada-LTS folder inside the webapps?

I ask because when I do the mapping, the application does not open.

**Comment by Limraj** [comment] 2023-04-05 16:06
@odenisnobre 
If the folder is properly structured and has the correct configuration files (e.g. web.xml, context.xml), tomcat will recognize it as a web application. 

`I ask because when I do the mapping, the application does not open.`
I don't understand this statement? You modify the contents of this webapps folder which is defined as bind volumes and the changes are visible in the container. Doesn't it work that way?

**Comment by odenisnobre** [comment] 2023-04-05 16:11
I am mapping this structure:
![image](https://user-images.githubusercontent.com/8119694/230140432-00325519-24de-468b-b110-336e331f1a7f.png)


Is correct?

**Comment by Limraj** [comment] 2023-04-05 16:14
I don't understand what mapping means to you? It is enough that to the webapps folder, which is defined as bind volumes, copy the wara with the new version, or the folder. Then the changes should be visible from the container.

If you had the old version running before, you started the new one, the database structure is changed and you try to run the old version again, it won't work because of the changed database structure.

edit:
If you modified the old folder behind the file because you wanted to customize the appearance of the application, then if these modified files have not been changed, you can skip them when rewriting the files. You can also move files after stopping the container so that nothing interrupts the process.

You have to tell me what exactly you want to achieve, because that's how we can discuss and discuss.

**Comment by odenisnobre** [comment] 2023-04-05 16:30
I'm almost at the end.
I think now the problem is in the database as the version has changed the structure as well.

But how to preserve data from the old version?

**Comment by odenisnobre** [comment] 2023-04-05 16:35
What I don't understand:

The folder structure is ok and when I access the URL:
![image](https://user-images.githubusercontent.com/8119694/230146137-aedaf813-9f2d-4d8c-bda9-77ec798cf0a9.png)

**Comment by Limraj** [comment] 2023-04-05 17:06
@odenisnobre,
1. Which version do you want to run?
If you are unable to run this version, you can check it in:
`\webapps\Scada-LTS\WEB-INF\classes\version.properties`
You need to first determine which version you want to run.

2. I reported this in a previous issue where you asked about configuring volumes. I said you have to be careful here. On the latest version, you can export configurations and import on a clean database on old version.
2.1. Run lastest version, and export project, generate zip file with configuration:
![export_1](https://user-images.githubusercontent.com/35842300/230147391-87b89015-fe1b-4d9a-8ce0-23e456d5ba50.png)
2.2. Next login to mysql server container:
`docker ps`
Copy container_id witch mysql server and:
`docker exec -it container_id /bin/bash`
Next backup old database: 
`mysqldump --single-transaction --routines --triggers -u root -proot scadalts > /var/lib/mysql/scadalts-$(date +%Y-%m-%d-%H).sql;`
Next drop database scadalts:
`mysql -u root -proot -e "drop database scadalts";`
And create empty scadalts:
`mysql -u root -proot -e "create database scadalts";`
Move *.sql from db_data to other path;  
2.3 Run old version application and import project:
![import_2](https://user-images.githubusercontent.com/35842300/230150689-e581a95a-8dc8-4848-98f2-75641a7fdfea.png)

However, problems may arise. If you don't have a strong case to go back from a newer version to an older version, then maybe there's no point in doing it.

**Comment by odenisnobre** [comment] 2023-04-05 17:13
I went back to the old version (of the folder) and the application did not load

**Comment by Limraj** [comment] 2023-04-05 17:20
@odenisnobre 
If you want us to get anywhere, try to follow my instructions. If something is unclear, ask. I asked you to check in this file what version you are trying to run. Second, the question is do you really need to go back to an older version? If you must, I have given instructions on how to transfer data from the new database structure to the old one, you must follow it. I'm just wondering if it's justified. The new version has a lot of improvements, including the character encoding reported here.

**Comment by Limraj** [comment] 2023-04-06 07:14
@odenisnobre I understand you have no more questions/problems, can you close the issue?

**Comment by odenisnobre** [comment] 2023-04-06 10:49
Sorry for the inconvenience.
I think I made a lot of confusion, the fact is that when I updated the stack in the portainer (docker) the application did not go up anymore
As I had made several customizations, I would go back to the previous version but, as suggested, it would not be the best option.

But no problem, I'll keep the new version but the most important thing I need is to keep the volume mapping.

I have to make my adjustments, so you can close the case, no problem.

**Comment by Limraj** [comment] 2023-04-06 11:02
@odenisnobre 
Just copy the changed files to the new version into webapps. If there is a problem, write to me, I'm closing this issue for now.

**Closed as completed by Limraj** 2023-04-06 11:02 UTC
Labels: community
