### ISSUE TITLE
A server error has occured. More information may be available in the console.

### ISSUE THREAD

**Issue by AristotelesMelo** [SCADA-LTS/Scada-LTS#2608] opened 2023-07-06 14:03 UTC
**Describe the bug**
I installed 2.7.5.3 (jdk-11/ Dbeaver23 / following the guidance presented on the site.

After installation Scada-LTS starts asking for login and password. So far so good

Any operation I try to do I get the message:

![erro connect](https://github.com/SCADA-LTS/Scada-LTS/assets/50463404/390475f3-0b70-479e-a4f2-94a45a656955)
![erro install](https://github.com/SCADA-LTS/Scada-LTS/assets/50463404/91b16a18-db44-4a9d-b5bd-2849a86d3ea6)

All navigation in scada-lts is compromised by showing these errors.

**Comment by Limraj** [comment] 2023-07-06 14:06
Hi @AristotelesMelo,
Session in tomcat lasts 30 minutes, after that you are automatically logged out of the application and then you get this message.
It's best to open a topic first at: https://github.com/SCADA-LTS/Scada-LTS/discussions
If it turns out that there is something to fix, then issue.

Regards,
Kamil Jarmusik

**Comment by AristotelesMelo** [comment] 2023-07-06 14:34
Hi Kamil

 

Thank you for your attention.

I didn't quite understand your answer.

These error messages appear constantly since the applications are started(tomcat + scada-lts). 

In the link you sent me I did not read any guidance to the problem I encountered.

 

 

De: Kamil Jarmusik ***@***.***> 
Enviada em: quinta-feira, 6 de julho de 2023 11:07
Para: SCADA-LTS/Scada-LTS ***@***.***>
Cc: AristotelesMelo ***@***.***>; Mention ***@***.***>
Assunto: Re: [SCADA-LTS/Scada-LTS] A server error has occured. More information may be available in the console. (Issue #2608)

 

Hi @AristotelesMelo <https://github.com/AristotelesMelo> ,
Session in tomcat lasts 30 minutes, after that you are automatically logged out of the application and then you get this message.
It's best to open a topic first at: https://github.com/SCADA-LTS/Scada-LTS/discussions
If it turns out that there is something to fix, then issue.

Regards,
Kamil Jarmusik

**Comment by Limraj** [comment] 2023-07-06 14:39
I don't understand what constantly means, as I said, if you are not logged in to the application, you will get this message.
Describe exactly what you do when this error occurs.
In the future, in order to be able to help, you must try to describe, show the problem in such a way that the other person can reproduce it. It is best to describe in points the steps that lead to the error.

The cause of this error may also be different. If, for example, despite my instructions, the migration failed, you will get all kinds of errors.

1. Show what the query returns:
select * from schema_version;

2. Send me logs from ".../Program Files/Scada-LTS/tomcat/logs"

**Comment by AristotelesMelo** [comment] 2023-07-06 15:35
I – Login OK



 

II – Open scada-lts ok



 

III – Try save any alteration.

 



 



De: Kamil Jarmusik ***@***.***> 
Enviada em: quinta-feira, 6 de julho de 2023 11:40
Para: SCADA-LTS/Scada-LTS ***@***.***>
Cc: AristotelesMelo ***@***.***>; Mention ***@***.***>
Assunto: Re: [SCADA-LTS/Scada-LTS] A server error has occured. More information may be available in the console. (Issue #2608)

 

I don't understand what constantly means, as I said, if you are not logged in to the application, you will get this message.
Describe exactly what you do when this error occurs.
In the future, in order to be able to help, you must try to describe, show the problem in such a way that the other person can reproduce it.

**Comment by Limraj** [comment] 2023-07-06 15:50
I'm sorry but I really don't know how to help you, you don't listen to instructions, the information you provide is not enough...

1. Show what the query returns:
select * from schema_version;

2. Send me logs from ".../Program Files/Scada-LTS/tomcat/logs"

**Comment by Limraj** [comment] 2023-07-07 19:25
Hi @AristotelesMelo,
You don't know how to query the database, I thought you wrote that you were adding some fields/columns in the database, maybe I misunderstood you.If you don't know how to query the database:
1. You must have some client, in windows it can be [workbench -> select windows](https://dev.mysql.com/downloads/workbench/) , but I prefer [DBvear](https://github.com/SCADA-LTS/windows-installer/blob/master/README.md#12-client-mysql---dbeaver-optional---).
2. Then create a tutorial connection with:
[configuration new connection](https://github.com/SCADA-LTS/windows-installer/blob/master/README.md#12-client-mysql---dbeaver-optional---)
For server database from installer port: 3308, empty password:, user:root. If you have a workbench, the configuration is analogous, if you have a problem, let me know.
3. Create a new SQL query and execute this query based on it:
3.1. 'Set as default' for database scadalts:
![Screenshot 2023-07-07 at 21 14 18](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/1a1bec33-adc9-4e49-8a14-1bf0275bee57)
3.2. Next on main menu, click arrow for SQL, and click 'New SQL script':
![Screenshot 2023-07-07 at 21 17 14](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/5ba0be4b-cf0d-4b7d-bb22-7ce0efe46ccd)
4. Send me logs from ".../Program Files/Scada-LTS/tomcat/logs" -> It's about logs catalina.out/mango.log/catalina.err which are non-empty.
5. If we are already trying to solve your problem, then do not do things yourself, if you do not know how to fix something or how to perform a given step, just ask so that I also know exactly the state of what you have, otherwise we will not come to a solution to the problem.

Let me know if you have trouble following these steps. Most likely, the problems come from the fact that the migration failed, and then such errors can appear.

Regards,
Kamil Jarmusik

**Comment by AristotelesMelo** [comment] 2023-07-10 11:35
Hi Jamil

 

Once again I want to thank you for your attention.

After your help, version 2.75 is working.

 

As a suggestion, I think it would be interesting for the next versions to keep MySQL independent of Tomcat.

 

BR

Aristóteles

 

De: Kamil Jarmusik ***@***.***> 
Enviada em: sexta-feira, 7 de julho de 2023 16:25
Para: SCADA-LTS/Scada-LTS ***@***.***>
Cc: AristotelesMelo ***@***.***>; Mention ***@***.***>
Assunto: Re: [SCADA-LTS/Scada-LTS] A server error has occured. More information may be available in the console. (Issue #2608)

 

Hi @AristotelesMelo <https://github.com/AristotelesMelo> ,
You don't know how to query the database, I thought you wrote that you were adding some fields/columns in the database, maybe I misunderstood you.If you don't know how to query the database:

1.	You must have some client, in windows it can be workbench - <https://dev.mysql.com/downloads/workbench/> > select windows , but I prefer DBvear <https://github.com/SCADA-LTS/windows-installer/blob/master/README.md#12-client-mysql---dbeaver-optional---> .
2.	Then create a tutorial connection with:
https://github.com/SCADA-LTS/windows-installer/blob/master/README.md#12-client-mysql---dbeaver-optional--- . For server database from installer port: 3308, empty password:, user:root. If you have a workbench, the configuration is analogous, if you have a problem, let me know.
3.	Create a new SQL query and execute this query based on it:
3.1. 'Set as default' for database scadalts:
 <https://user-images.githubusercontent.com/35842300/251836403-1a1bec33-adc9-4e49-8a14-1bf0275bee57.png> 
3.2. Next on main menu, click arrow for SQL, and click 'New SQL script':
 <https://user-images.githubusercontent.com/35842300/251836935-5ba0be4b-cf0d-4b7d-bb22-7ce0efe46ccd.png> 
4.	Send me logs from ".../Program Files/Scada-LTS/tomcat/logs" -> It's about logs catalina.out/mango.log/catalina.err which are non-empty.

Let me know if you have trouble following these steps. Most likely, the problems come from the fact that the migration failed, and then such errors can appear.

Regards,
Kamil Jarmusik

**Comment by Limraj** [comment] 2023-07-10 14:01
Hi @AristotelesMelo ,

I repeat to you once again, do not take any steps yourself, but try to follow what I write, unless you do not want help and want to do something yourself. What you're doing makes no sense. 
You're about to have a strange problem again, and then I won't be able to help you, because you don't really want help, you want to do things yourself.

Regards,
Kamil Jarmusik

**Comment by Limraj** [comment] 2023-07-10 14:04
I'm closing this topic, if you have a problem, then try to do what I've already written to you, and if not, then continue on your own. 
I never told you to try to install any other version. There are two to choose from, either stable 2.6.18 or beta/development 2.7.5.3. There is no other recommended version to install at the moment.

**Closed as completed by Limraj** 2023-07-10 14:04 UTC
Labels: community
