### ISSUE TITLE
 Alarm cannot be recognized

### ISSUE THREAD

**Issue by GabrielTec251** [SCADA-LTS/Scada-LTS#2745] opened 2023-10-25 13:59 UTC
When the alarm is generated, there is no individual alarm consideration button and consideration of all alarms does not work

https://github.com/SCADA-LTS/Scada-LTS/assets/138117880/2e035190-b13d-4863-8470-762c108727fa

v2.7.6.1
win 10

**Comment by Limraj** [comment] 2023-10-25 14:18
Hi @GabrielTec251,
 You can only acknowledge events that have gone to the normal state (or is No RTN), but you can silence an active event. Does this solve the problem?

Regards,
Kamil Jarmusik

**Comment by GabrielTec251** [comment] 2023-10-25 14:31
He just licenses it, I can't recognize it.

Note: I think a more interesting behavior would be to be able to recognize it normally, but it would only disappear from the list when it was inactive, in the case when you recognize it it just informs you that it was recognized and silences the alarm

**Comment by Limraj** [comment] 2023-10-25 14:38
The acknowledge function is intended to make people click this button if the problem is already solved. Therefore, if the event does not reach the "return to normal" status, it cannot be acknowledged. 
Imagine what would happen if someone confirmed an active problem and then it disappears from this list and nobody hears about it... that's what the mute function is for, it doesn't make the event disappear from this list, it can only mean that someone is dealing with it . Once the problem is resolved, it goes back to normal and can be acknowledged.

**Comment by GabrielTec251** [comment] 2023-10-25 14:45
in fact it worked, however in relation to the operation, recognition is used to have control of who viewed it, for example, when it starts to alarm and the operator saw the alarm, it has to record that this operator was aware of the alarm, even if the problem has not been resolved

**Comment by GabrielTec251** [comment] 2023-10-25 14:52
In this case, the alarm would have these possible states:

acknowledged: the operator acknowledged the alarm;
the behavior should then be: Alarm stops with the sound, however if the defect has not been resolved, it continues in the alarm lists and in the graphical visualization list, allowing comments on the alarm and its visualization, and when it is resolved it should disappear;


second case: unrecognized alarm: in this case the behavior would be, audible alarm remains active as long as the alarm is active, if the defect is resolved and the operator has not recognized it, it stops the sound, but continues in the list of alarms until it is Be aware of it, when it is recognized it disappears.

**Comment by Limraj** [comment] 2023-10-25 14:55
This results from our arrangements with the client... the name would also suit such an application, so that a person could finally confirm whether it is OK... we can add the date and the user who muted the event, this seems to reconcile these problems...

**Comment by GabrielTec251** [comment] 2023-10-25 14:56
there is a need for recognition even if the alarm is active, so that it is known which operator was aware of the alarm,

In an application with several operators, it is difficult to know who was aware of the alarm, information like this is important if an alarm goes off and it takes a long time for the maintenance team to be called quickly.

**Comment by Limraj** [comment] 2023-10-25 15:01
What do you think about providing a username and date to silence the alarm? I feel like this would achieve the things you mentioned at the lowest cost.

**Comment by GabrielTec251** [comment] 2023-10-25 15:01
![alarme](https://github.com/SCADA-LTS/Scada-LTS/assets/138117880/1a8af486-9276-4fe1-a8cd-b421ab917be4)
In this example, the alarm went off and returned to normal, only then can it be recognized, so at the reporting level, it is as if during the entire period that the alarm was active, no one noticed it, only after it was resolved

**Comment by GabrielTec251** [comment] 2023-10-25 15:05
A solution is being developed for this in the graphics area, which will have the behavior I mentioned above, I can share it later and you can adapt it to a native function

what do you think?

**Comment by Limraj** [comment] 2023-10-25 15:07
@GabrielTec251 I asked a question and I expect you to address it unless you are not willing to cooperate. At the moment there is no continuous alarm signal, but there is an issue to implement the possibility of configuring different alarms.

**Comment by GabrielTec251** [comment] 2023-10-25 15:10
OK, I'll analyze whether it works and whether it will be viable.

and over the alarm, he continued making some changes to the page.tag file
I managed to play the alarm, it continued

**Comment by Limraj** [comment] 2023-10-25 15:22
Generally speaking, a person should always decide to completely remove an event from the list. The system may make mistakes and some failure may occur. We can add the username and date when the user mutes this event, which may mean it is being addressed, or the issue is known and not being addressed at this time. 

I am not a decision person, if something requires a lot of work, we invite you to cooperate: scadalts-support@softq.pl

**Comment by Limraj** [comment] 2023-10-25 15:27
I opened a new one and closed this one: https://github.com/SCADA-LTS/Scada-LTS/issues/2746

**Closed as completed by Limraj** 2023-10-25 15:27 UTC
Labels: community

**Comment by Limraj** [comment] 2023-10-25 23:16
Pending alarms:
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/6cbe72b9-2391-4012-a5ee-7464ef499932)

Search:
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/11604f76-fe27-4ae4-869a-278e0156dfaf)

@GabrielTec251 I would suggest adding an 'Accepted' function that would work as follows:
1. It is only available for Active events, when acknowledge is not available;
2. It has the same icon as acknowledge, but a different signature;
3. An Accepted column has been added to the Pending and Search tables, displaying the username and acceptance date;
4. A given event can only be accepted once, by one person;
5. When it comes to notifying the highest alarm for a given user, it would work exactly like the silence function, with the difference that every user can see it;
6. Accepted events do not disappear from the pending list;
7. If the event goes to the 'Return to normal' state, then the 'Acknoledged' function is displayed and 'Accepted' disappears.

**Comment by Limraj** [comment] 2023-10-26 07:07
Hi @GabrielTec251,
Will this be ok?
