### ISSUE TITLE
Showing scripts in graphical view

### ISSUE THREAD

**Issue by jmuguruza** [SCADA-LTS/Scada-LTS#2034] opened 2022-01-08 10:49 UTC
I have created a .json file and a background image in order to preview one part of a project.
I defined 9 different HTML data points and 9 scripts. Now I want to show an output value (arbitrary value of 100 decided by me) at the output box after "Caudal de Aire:". This integer value comes from one of the nine scripts defined at the .json file.
I am not able to see that value in graphical views; the script declaration at the file must be wrong.
![json](https://user-images.githubusercontent.com/78322990/148641386-e2caeaf4-70a6-4f93-aa91-7c34bec7915d.JPG)
![graphical_view](https://user-images.githubusercontent.com/78322990/148641389-b254426d-223c-47e8-9a4d-b99333aa8eb5.JPG)

Does anyone know how to define it in the .json file?

Thanks in advance

**Comment by Limraj** [comment] 2022-01-10 12:12
Hi @jmuguruza,
1. If you would like to return a constant value there, it is enough in the script:
"return 100";
2. If you would like to return there the current point value that is set in this component, the script will suffice:
"return this.value";
You also have access to other point data here, for example:
"return point.name + ''" or 
"return point.xid + ''" and other

**Comment by jmuguruza** [comment] 2022-01-10 12:23
All right. Thank you for your help @Limraj !!!

**Comment by Limraj** [comment] 2022-01-10 12:43
@jmuguruza No problem, do you have any other questions?

**Comment by Limraj** [comment] 2022-01-10 16:58
@jmuguruza Can I close this topic?

**Comment by jmuguruza** [comment] 2022-01-10 20:13
Yes, by the moment everything is ok.
Thanks!

**Closed** 2022-01-10 22:24 UTC
Labels: community

**Comment by jmuguruza** [comment] 2022-01-13 20:51
Now I want to show at the inputs box an integer value from OpenPLC.
In the case of "Caudal de Purga", I gave it a value of 95145 in OpenPLC Editor and uploaded the .st file to OpenPLC.
At the .json file I defined the script like this:
"script":"return(\"<p style='font-size:25px'>\" + parseFloat(this.value).toFixed(0) + \"<\/p>\") ",

Is there something wrong or I might have made another mistake?

**Comment by jmuguruza** [comment] 2022-01-13 20:58
Now I want to show the variable "Caudal de Purga" at the input box; this variable come from OpenPLC.
I defined it as an integer in OpenPLC Editor, initialized with value 95145. 
So I would like to see that number at the Scada graphical views. 
I used this instruction at the .json file when defining the script:

"script":"return(\"<p style='font-size:25px'>\" + parseFloat(this.value).toFixed(0) + \"<\/p>\") "

Is there anything wrong or I might have made another mistake?

**Comment by Limraj** [comment] 2022-01-13 21:56
hello @jmuguruza,
The problem in your definition is that the whole property "script" is one string, the problem is with it + and using ", lower level denoted by `\"` (nesting), try: 
`"script":"return(parseFloat(this.value).toFixed(0) + \"<\/p>\");",`

**Comment by jmuguruza** [comment] 2022-01-13 22:33
I still got the same result; a 0.
![Captura](https://user-images.githubusercontent.com/78322990/149419528-1f575718-eaad-4ee7-939e-f58f2e15267a.JPG)

**Comment by Limraj** [comment] 2022-01-13 23:08
@jmuguruza Could you please send me the entire system configuration by e-mail: kamil.jarmusik@softq.pl? (To do this, go to 'Import / Export' -> 'Export Project (Download)' section -> 'Export Project' button
1. As for the value 0:
try setting 
`return this.value `
there, although it will probably be 0. Another possible cause is something wrong with the connection. If you send me the configuration, it will be easier for me to help. You can also describe exactly in the email what you set up in OpenPLC.
2. As for the appearance of this value, there must be something wrong with the html / css styles structure in the view definition.

**Comment by jmuguruza** [comment] 2022-01-16 11:15
My situation now is the following:

1- I have created an .st file, with memory addressing that I did not do before and the monitor shows the following:
![monitoring](https://user-images.githubusercontent.com/78322990/149657500-f57b2976-5545-4f2f-ba1d-8f0b597ded76.JPG)

2- I changed a little bit the .json file, 'pointLocator' arguments at the 'dataPoints' part. These arguments are 'range', 'modbusDataType' and 'slaveID'.

3- I import the .json file at the 'Import/Export' menu and get this values:
![graphical_views](https://user-images.githubusercontent.com/78322990/149657619-04615ae3-a6da-49f6-bd09-88bfe44fd048.JPG)

**Comment by Limraj** [comment] 2022-01-16 23:29
Hello @jmuguruza 

I think it's a matter of configuring the correct registers, addresses, and types, in Scada you change the address using the offset parameter (0-65535), then you have 4 types of registers:
1) Coins status - read/write 1 bit register
2) Inputs status - read 1 bit register
3) Holding register - read/write 16 bit register
4) Input register - read 16 bit register

and what you changed modbusDataType to test yourself and determine these settings, type, register and addresses, you can use the section to test the connection:
![point_locator_test](https://user-images.githubusercontent.com/35842300/149682187-eded65f2-4d20-4cb8-811a-e8157a426331.png)

Modbus documentation
https://modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf

Greetings,
Kamil Jarmusik

**Comment by jmuguruza** [comment] 2022-01-17 10:23
Hi @Limraj 

I defined the 7 inputs as Input Registers (read) in the .json file and the 2 outputs as Holding Registers (read/write).

Now I don't know how to deal with the offset. How should I configure that parameter?

**Comment by Limraj** [comment] 2022-01-17 10:44
Hey @jmuguruza , 
each register type has the addresses 0-65535. See yourself for documentation, I also showed you how to test it in the Scada, you have to look into the program in which you configure points and look for something that may be responsible for it, in my opinion you can try extreme addresses, probably by default either addresses from 0-65535 (try 0, 1, 2, 3...) or 65535-0 (65535, 65534...), maybe it has to do with "location" or that .st file that you defined. 

Greetings,
Kamil Jarmusik

**Comment by jmuguruza** [comment] 2022-01-17 11:58
Fine, I think that I solved this problem.

Thank you once again @Limraj.

**Comment by jmuguruza** [comment] 2022-01-23 08:36
Hi @Limraj, one last thing. I achieved this in Scada-LTS:
![scada](https://user-images.githubusercontent.com/78322990/150670712-8fd20c05-1517-46f1-b5dc-563a6e2bffa8.JPG)

I am able to see all the values in the graphical views, but can not receive those two output variables. They are defined this way:
![script](https://user-images.githubusercontent.com/78322990/150670790-1fcdc8cc-a3dd-42ab-817b-18cf8f2e76fa.JPG)

Then the data points are defined as 2 Byte int signed holding registers and I get this in OpenPLC:
![monitoring (1)](https://user-images.githubusercontent.com/78322990/150670720-8137c39a-6e6c-4afc-b975-284406666037.JPG)

**Comment by Limraj** [comment] 2022-01-23 12:13
Hi, 
I don't quite understand, because in these scripts you return the constant values ​​100 and 57087, so how come you want the openplc value there? You need to change to this.value there, but I already wrote about that...

Greetings,
Kamil Jarmusik

**Comment by jmuguruza** [comment] 2022-01-23 16:34
The input variables come from OpenPLC and I use this.value and get those values, but now I am writing myself that output value of 100 and want to send it to OpenPLC. That is what I did not manage to do.

**Comment by Limraj** [comment] 2022-01-23 18:38
To enable the value to be changed:
1) The first shorter solution, you need to set the point as settable, read / write register, and create a 'simple point' component on the view with this point, and select the "Display controls" parameter in it. Then, after hovering over the point, you should be able to change the value. This solution is rather recommended in case there is a problem, let me know.

2) Another solution that requires more steps but uses scripts:
a) create datasource as ds_1 (virtual) and datapoint (numeric, settable, no change) as dp_to_read;
b) create script as script_write in the scripts tab, adding datapoint dp_to_read as val_read to the context and using a special function there
`val_2.writeDataPoint ('DP_OPENPLC_XID', val_read.value); `
![Screenshot 2022-01-23 at 19 25 13](https://user-images.githubusercontent.com/35842300/150692482-c1277a0a-4189-4704-9eae-726ba04ff63e.png)
c) then creating two components on the view for setting values, 'simple point' and setting dp_to_read in it, and component 'Button (script)' with script_write script to change the value.

Greetings,
Kamil Jarmusik

**Comment by jmuguruza** [comment] 2022-01-23 20:40
If I select one of the two output values and click on "Point details" then I can set a value manually and get it in the OpenPLC monitoring. It works with a value of 100, but when writing 57087 it does not work (both are defined as integers).
![a](https://user-images.githubusercontent.com/78322990/150697199-ba43431d-e072-4d0e-93a8-a0763481f369.JPG)
![b](https://user-images.githubusercontent.com/78322990/150697201-a8a21dc0-0d3c-4aaf-9fa1-65e26e855a23.JPG)

**Comment by Limraj** [comment] 2022-01-23 22:47
Everything I have told you so far should enable you to solve these types of problems. The other thing is that you don't listen to the instructions, so act your way. I can't help you any more. Greetings.

**Comment by Limraj** [comment] 2022-01-25 20:14
@jmuguruza 
Hey, did you deal with the problem?

**Comment by jmuguruza** [comment] 2022-01-28 17:59
For the last output variable (57087) no, the program did not let me set a value like that one.
But it was part of my final degree project, that I finished some days algo, so do not worry.
Thank you for your help this weeks :-)
