### ISSUE TITLE
DataSource Create Button/Option not show

### ISSUE THREAD

**Issue by odenisnobre** [SCADA-LTS/Scada-LTS#2724] opened 2023-10-15 22:44 UTC
After creating some Datasources manually and via API I noticed that the button to create new datasources via graphical interface was no longer available.

![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/8375281e-af0c-4e64-99d3-f2bde83cb9b2)
This applies to the `configurationDescription `field in Point Locator, which cannot be null, and in `OPCPointLocatorVO `it was null by default. This also applies to classes such as:

- [x] ASCIIFilePointLocatorVO,
- [x] ASCIISerialPointLocatorVO,
- [x] Dnp3PointLocatorVO,
- [x] DrStorageHt5bPointLocatorVO,
- [x] NodaveS7PointLocatorVO,
and:
- [x] OPCPointLocatorVO

This field has been defined for these types.

- [x] Class `LocalizableMessageOutTag  `did not handle the situation where message is null, this has also been corrected.

**Comment by Limraj** [comment] 2023-10-16 09:46
Hi @odenisnobre,
1. What version are you using?
2. Can you show what you have in: "right click on the website -> inspect -> console and network tab"
3. Does the problem also occur on another browser?
4. Can you go to the SQL tab and run the queries and show what it returns:
select count(id) from events;
select count(id) from pointValues;
select * from dataSources;

Regards,
Kamil Jarmusik

**Comment by odenisnobre** [comment] 2023-10-16 12:06
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/89f01f16-85ba-469a-aa5e-c67796e98d98)

![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/06c66512-ff14-48c1-85a4-036ebffb0cba)

The problem occur in other browsers.

![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/c94ba80e-2169-4647-815d-7e70c8c6f086)
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/b7341833-912f-4189-8487-2d06e928d1c2)
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/26d80dc6-8bef-409e-ad2d-8423afe02b65)

**Comment by Limraj** [comment] 2023-10-16 12:50
1. Can you show what you have in: right click on the website -> inspect -> console tab?
2. What is node-env? Have you looked on the Internet what causes the error NS_ERROR_NET_PARTIAL_TRANSFER / NS_BINDING_ABORDED?
3. When did you notice this problem? I understand that it worked before, does it depend on the version?
4. If you restart tomcat on the server, does the problem still occur?
5. You can export the project using the Import/Export function then check if the problem is related to one of these Data Source types, remove all of them and add one data source type first, if ok then remove and add the second data source type, if ok then add another data source yes to be the situation you present with two data sources and check if the problem still occurs. If not, import the project with a previously exported file and check if the problem still occurs.

I recommend making annotations to the questions (Re./Ref. 1, Ref. 2, etc.) so that we can understand each other more easily.

Regards,
Kamil Jarmusik

**Comment by Limraj** [comment] 2023-10-16 12:58
Perhaps a fix will solve this problem (if this problem with OPC DA):
https://github.com/SCADA-LTS/Scada-LTS/issues/2715
in version 2.7.6.1

You can check it as follows:
1. Install Docker Compose:
[Docker Compose Windows installation](https://github.com/SCADA-LTS/Scada-LTS/wiki/Getting-started-Development-%E2%80%90-Windows#4-docker-compose-)
[Docker Compose Linux installation](https://github.com/SCADA-LTS/Scada-LTS/wiki/Getting-started-Development-%E2%80%90-Linux#4-docker-compose-)

2. How use commands:
[Docker Compose Tutorial](https://github.com/SCADA-LTS/Scada-LTS/wiki/Scada-LTS-docker-compose-tutorial#Commands)

3. Download file [docker-compose.yml](https://github.com/SCADA-LTS/Scada-LTS/blob/develop/docker-compose.yml) and change property image on **pr-2683** (from latest):
`image: scadalts/scadalts:pr-2683`
**pr-2683** is the pullrequest identifier:
https://github.com/SCADA-LTS/Scada-LTS/pull/2683

Regards,
Kamil Jarmusik

**Comment by odenisnobre** [comment] 2023-10-16 13:03
Answers:
1: 
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/0173c6ca-91fd-4bab-8436-19a00e150a7d)

2: I didn't find anything related, at least I couldn't understand the context

3: In fact, the problem occurred right after creating a new datasource via API

4: Even restarting the container the error persists

5: The error occurs when adding an OPC DA type datasource

**Comment by odenisnobre** [comment] 2023-10-16 13:06
https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/26a61f08-f434-4a0e-b931-798d6a98e93f

**Comment by odenisnobre** [comment] 2023-10-16 13:13
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/92e2b73b-3d18-4794-945d-59f10ea51909)


the error continues after updating to the new build

**Comment by Limraj** [comment] 2023-10-16 13:16
You may have problems configuring these connections in Docker, so I prepared a war for you, it is not a production version, file [Scada-LTS_pre_2.7.6.1_NO_PRODUCTION.zip](https://github.com/SCADA-LTS/Scada-LTS/releases/download/v2.7.6/Scada-LTS_pre_2.7.6.1_NO_PRODUCTION.zip):

First stop tomcat, and delete or move the old ScadaBR/Scada-LTS folders and war file from tomcat/webapps, then extract the downloaded file, it will be the war file, and move it to tomcat/webapps, and start tomcat.

**Comment by odenisnobre** [comment] 2023-10-16 13:43
I made some changes to my docker compose to make it easier to use the .war file, but now it doesn't load the application.
Where could the error be?

```
# Docker compose file to manage your deployed images.
# Use MySQL server 5.7 and latest Scada-LTS local build.
# Using attached webapps folder as developer you will be able to modify the static content from host os.
# Attach shell to stop the tomcat instance and then you will be able to run in JPDA mode.
version: '3'
services: 
    database:
        container_name: db
        image: mysql/mysql-server:8.0.32
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=scadalts
        expose: ["3306"]
        volumes:
            - /home/noobres/volumes-docker/scadalts/mysqldata:/var/lib/mysql:rw
            - /home/noobres/volumes-docker/scadalts/mysqlconfig:/etc/mysql:ro
        command: --log_bin_trust_function_creators=1
    scadalts:
        container_name: scada
        image: scadalts/scadalts:pr-2683
        environment:
            - CATALINA_OPTS=-Xmx512m -Xms512m
        ports: 
            - "8080:8080"
        depends_on: 
            - database
        expose: ["8080", "8000"]
        volumes:
            - /home/noobres/volumes-docker/scadalts/aplicacao/logs/:/usr/local/tomcat/logs:rw
            - /home/noobres/volumes-docker/scadalts/aplicacao/app/:/usr/local/tomcat/webapps:rw
        links:
            - database:database
        command:
            - /usr/bin/wait-for-it
            - --host=database
            - --port=3306
            - --timeout=30
            - --strict
            - --
            - /usr/local/tomcat/bin/catalina.sh
            - run

**Comment by odenisnobre** [comment] 2023-10-16 14:07
I configured the new .war file but the error still persists.

**Comment by odenisnobre** [comment] 2023-10-16 14:34
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/4c607223-d7ee-47ca-92c6-194c44a9e001)

**Comment by Limraj** [comment] 2023-10-16 15:20
@odenisnobre 
1. Have you done anything with this before (OPC DA)? Since when have you had a problem with this?

2. Can you check this on version 2.6.18?
`image: scadalts/scadalts:v2.6.18`

3. Show me what you have set in this Data Source, what parameters? Show in Scada UI;
4. Send to me all logs from tomcat/logs;
5. What do you use to launch the application? Docker, are you using the war I prepared locally?
6. Have you tried creating this data source from the UI?
I wrote here that creating Data Source via API is limited to these types: 
https://github.com/SCADA-LTS/Scada-LTS/issues/2518
```
This feature is currently limited and you can create the following Data Source this way:
dataSourceTypeId = 1 (VirtualDataSource)
dataSourceTypeId = 3 (ModbusIpDataSource)
dataSourceTypeId = 5 (SnmpDataSource)
dataSourceTypeId = 9 (MetaDataSource)
```

If creating OPC DA via UI works, then you need to change the content of this issue, it only concerns creating this Data Source via API, maybe we will find time to extend this API for more types, you can also add add returns 400 for unsupported types. Then there is no point in answering other questions 1-5, you just need to correct the title and description of this issue.

**Comment by odenisnobre** [comment] 2023-10-16 15:58
Well, let's go.

In short, the error occurs when creating the OPC-DA interface via UI or via API, the problem occurs both.
But in the end the error is not when creating the Datasource but when creating the DataSource tags

**Comment by Limraj** [comment] 2023-10-16 16:17
@odenisnobre 
1. If the problem occurs after creating this Data Source via UI, you need to answer my questions. If it breaks like this after adding this data source via UI, it would be very strange. 
"creating Data Source via UI" -> Open Scada-LTS in browser, login as admin, go to Data Sources, select "OPC DA" and click on 'Add':
![Screenshot 2023-10-16 at 18 14 40](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/9418548b-7160-4020-ba49-8ffd66286c0c)
Next set fields and click on 'Save';

3. "creating the DataSource tags"... can you explain it? I don't understand what you mean by data source tags...

edit:

Okay, my mistake, I see in this video, then you need to change the title and add a scenario that after adding tags/point something crashes. I saw you added two tags there at once, could you try selecting one tag there?

**Comment by odenisnobre** [comment] 2023-10-16 16:22
If you notice in the video below, you will see that the issue is during the creation of the points and not necessarily in the datasource

https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/cb04fdfa-c9cb-4d45-a8e8-0d4ca8dd4109

**Comment by Limraj** [comment] 2023-10-16 16:44
@odenisnobre 
Before you create an issue, try to describe the problem as precisely as possible. I need written information, I always need logs (tomcat/logs), I need to add a script, step by step, then you can also add this video (However, video as a last resort is too time-consuming to watch). See, we lost hours to determine that the problem concerns adding tags in OPC DA, which should be immediately described in the issue content. If you used OPC DA, API, whatever and we already talked about it, you need to go back to this information and make some reference, e.g. it stopped working for me with the version, or I didn't use it before.

**Comment by odenisnobre** [comment] 2023-10-16 16:54
Well, sorry about that.

I think you already understand the problem even with this confusion I made.

With the version you sent me, in addition to the button not being visible, other datasources are also not visible.

If you still need more information, let me know.

Again, sorry.

**Comment by Limraj** [comment] 2023-10-16 16:58
@odenisnobre It's not about apologizing, it's about effective communication.
You need to complete the information in the issue, give an appropriate title, add a script, etc. so that the person who comes across it after some time does not have to browse through these messages, and you did not provide all the information I asked for, so it also needs to be included there.

**Comment by odenisnobre** [comment] 2023-10-16 17:01
We can close the case.

**Comment by Limraj** [comment] 2023-10-16 17:05
If you don't want to be helpful, don't count on others to give you their time.

**Comment by odenisnobre** [comment] 2023-10-16 17:09
The problem is not the usefulness but the confusion that is creating the case.
The closure request is due to the confusion that has arisen around something, which has already been analyzed, so simple.

I sincerely apologize for that.

If you think it's better and so as not to extend this case any further, we can remove it and start another with less confusion.

**Comment by Limraj** [comment] 2023-10-16 17:18
@odenisnobre You have noticed a problem that exists, you just need to add this information in the issue content and that's it, instead of getting offended. If the information is completed, there is a greater chance that someone will take care of it.

In addition to what you have already written, you need:
1. Tomcat logs;
2. Information whether you have used this data source before, because from what I remember you have already used it, or at least tried to help someone else?

If you don't want to do it in this issue, we can close it, but you need to create a new one with the information added. The more precisely you describe and test the problem, the greater the chance that someone will take care of it. You always need:

1. Scenario;
2. Logs;
3. Scada-LTS Version, it is worth adding here if you have used this function before;
4. Here you can also add information whether you used the [installer](https://github.com/SCADA-LTS/windows-installer), docker, or installed it yourself;

You can use our templates (bug) to make it easier to fill in this data.

**Comment by odenisnobre** [comment] 2023-10-16 17:24
OK, let's continue here.

An OPC-DA configuration test was previously carried out, but I believe it was in previous versions that I don't remember, well before version 2.7.6 build 5974585195
[logs.zip](https://github.com/SCADA-LTS/Scada-LTS/files/12919809/logs.zip)

Below is the tomcat log.

**Comment by Limraj** [comment] 2023-10-16 17:29
You need to complete the content of the issue, not in the comments, this will increase the chances that someone will take care of it.

You can further investigate whether you can add these tags individually, whether they need to be enabled in order to crash, whether they can be disabled and you can check some more scenarios, then it will make the work easier for the developer. If you can, check on v2.6.18.

I would check it myself, but I don't have a simulator at hand.

**Comment by odenisnobre** [comment] 2023-10-16 17:31
I will test the scenarios in version 2.6.18.

**Comment by Limraj** [comment] 2023-10-16 17:41
Can you edit this issue and add important information that we wrote about, and corrected title? I will be grateful...

**Comment by odenisnobre** [comment] 2023-10-16 17:42
I'll do the tests and make the changes.

**Comment by Limraj** [comment] 2023-10-16 17:46
Thank you very much. :) 

If it works on 2.6.18 I think we'll get the hang of it, if it doesn't work on 2.6.18 then that would mean it's probably always worked like this and might take too much time... we have other very important topics...

**Comment by Limraj** [comment] 2023-10-16 19:20
Okay,
It looks like I found the reason why loading the data source list fails after adding a point to Data Source OPC DA. So you don't need to complete it like that anymore, and the reason is not related to the tags. 
This applies to the configurationDescription field in Point Locator, which cannot be null, and in OPCPointLocatorVO it was null by default. This also applies to classes such as: 
- ASCIIFilePointLocatorVO, 
- ASCIISerialPointLocatorVO, 
- Dnp3PointLocatorVO, 
- DrStorageHt5bPointLocatorVO, 
- NodaveS7PointLocatorVO,
and:
- OPCPointLocatorVO

Similarly to how you tested earlier on Docker:
`image: scadalts/scadalts:pr-2725`
 you can test this pullrequest and let us know if it works OK, then we will merge to version 2.7.6.1.
https://github.com/SCADA-LTS/Scada-LTS/pull/2725

**Comment by odenisnobre** [comment] 2023-10-16 19:38
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/4361b83f-6614-4079-b0a6-30837dcf6095)

I tested with pr-2725 and the error persists.
Not only does the add datasource button appear but also the other datasources
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/0c1cb467-17e2-43ed-8e73-b5f7ae1d96a9)

![image](https://github.com/SCADA-LTS/Scada-LTS/assets/8119694/fa8b2a87-0ef2-455d-ae2d-c2aae1bd0665)

Would you be able to confirm if the build pro pr-2725 is the same 6496147414

**Comment by Limraj** [comment] 2023-10-16 20:56
You ran on an old image, there is not other option.
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/9a43d2e9-e0dd-48a9-8406-b499b407175a)
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/f1702be5-b6d5-4b50-ae19-dc997f9a54ec)
![image](https://github.com/SCADA-LTS/Scada-LTS/assets/35842300/014e2b30-fed3-468a-910d-dd9293f6f272)

It is not possible to have two versions of an image at a given image address at the same time. You can also try:
docker-compose pull scadalts

**Comment by odenisnobre** [comment] 2023-10-16 20:59
Very strange.
I'll see what I did wrong here.

**Comment by Limraj** [comment] 2023-10-16 21:04
Are you using this file? Removed this line:
`- /home/noobres/volumes-docker/scadalts/aplicacao/app/:/usr/local/tomcat/webapps:rw`
in:
```
# Docker compose file to manage your deployed images.
# Use MySQL server 5.7 and latest Scada-LTS local build.
# Using attached webapps folder as developer you will be able to modify the static content from host os.
# Attach shell to stop the tomcat instance and then you will be able to run in JPDA mode.
version: '3'
services: 
    database:
        container_name: db
        image: mysql/mysql-server:8.0.32
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=scadalts
        expose: ["3306"]
        volumes:
            - /home/noobres/volumes-docker/scadalts/mysqldata:/var/lib/mysql:rw
            - /home/noobres/volumes-docker/scadalts/mysqlconfig:/etc/mysql:ro
        command: --log_bin_trust_function_creators=1
    scadalts:
        container_name: scada
        image: scadalts/scadalts:pr-2683
        environment:
            - CATALINA_OPTS=-Xmx512m -Xms512m
        ports: 
            - "8080:8080"
        depends_on: 
            - database
        expose: ["8080", "8000"]
        volumes:
            - /home/noobres/volumes-docker/scadalts/aplicacao/logs/:/usr/local/tomcat/logs:rw
            - /home/noobres/volumes-docker/scadalts/aplicacao/app/:/usr/local/tomcat/webapps:rw
        links:
            - database:database
        command:
            - /usr/bin/wait-for-it
            - --host=database
            - --port=3306
            - --timeout=30
            - --strict
            - --
            - /usr/local/tomcat/bin/catalina.sh
            - run
```
And run again:
`docker-compose up scadalts`
After this it should work, but if you had followed the instructions I sent you earlier, there would be no problem now: (you used other version docker-compose.yml file)

> Perhaps a fix will solve this problem (if this problem with OPC DA): #2715 in version 2.7.6.1
> 
> You can check it as follows:
> 
> 1. Install Docker Compose:
>    [Docker Compose Windows installation](https://github.com/SCADA-LTS/Scada-LTS/wiki/Getting-started-Development-%E2%80%90-Windows#4-docker-compose-)
>    [Docker Compose Linux installation](https://github.com/SCADA-LTS/Scada-LTS/wiki/Getting-started-Development-%E2%80%90-Linux#4-docker-compose-)

> 2. How use commands:
>    [Docker Compose Tutorial](https://github.com/SCADA-LTS/Scada-LTS/wiki/Scada-LTS-docker-compose-tutorial#Commands)
> 3. Download file [docker-compose.yml](https://github.com/SCADA-LTS/Scada-LTS/blob/develop/docker-compose.yml) and change property image on **pr-2683** (from latest):
>    `image: scadalts/scadalts:pr-2683`
>    **pr-2683** is the pullrequest identifier:
>    [Release/2.7.6.1 #2683](https://github.com/SCADA-LTS/Scada-LTS/pull/2683)
> 
> Regards, Kamil Jarmusik

**Comment by odenisnobre** [comment] 2023-10-16 21:12
Sensational.
Now yes.
It worked smoothly.

I would like to externalize the Scada-LTS part so that I can make customizations.
```
- /home/noobres/volumes-docker/scadalts/aplicacao/app/:/usr/local/tomcat/webapps:rw
```

Would I have to download another .war file with this version of pr-2725?

**Comment by Limraj** [comment] 2023-10-16 21:19
Do you mean the issue with Docker works, and what about the errors from this issue? With displaying a list of data source types and all data sources in the list?



> Sensational. Now yes. It worked smoothly.
> 
> I would like to externalize the Scada-LTS part so that I can make customizations.
> 
> ```
> - /home/noobres/volumes-docker/scadalts/aplicacao/app/:/usr/local/tomcat/webapps:rw
> ```
> 
> Would I have to download another .war file with this version of pr-2725?

That parameter maps the tomcat/webapps location in the container to that of the host(system file your computer), so as a host you could throw war there and see the effects in the container, the container then does not see the tomcat/webapps location on itself, but uses the host's location.


This is how 'volumes' of the 'bind' type works in Docker. Operating on the host's file system can cause problems, for example saving tables in the mySQL server (tables in mysql are represented by files), that's why there is another type of 'volumes' called 'volume', then it works completely differently, you can't upload files from the outside in such a simple way (it works outside host file system), in addition it does not work without Docker running, but it retains the state from the container launch and has no limitations resulting from the use of the host file system.

**Comment by odenisnobre** [comment] 2023-10-16 22:09
Understood.
Well, overall, the solution was perfect.
The issue of volume mapping will be left for later.

Excellent job.
Thank you very much.

**Comment by odenisnobre** [comment] 2023-10-16 22:45
One more thing, which file or version of the .war file can I have this new configuration?

I returned the volume mapping, but the .war file I added is still with the old build.

**Comment by Limraj** [comment] 2023-10-17 06:00
If you add the line:
`- /home/noobres/volumes-docker/scadalts/aplicacao/app/:/usr/local/tomcat/webapps:rw`
then the container ignores its location `/usr/local/tomcat/webapps`, so it will not load the war related to the image version, but it will load what you put in your location: `/home/noobres/volumes-docker/scadalts/aplicacao/app/`, so if you had an old war there, then load the old war. Removing this line causes the container to use location `/usr/local/tomcat/webapps` and load the version of war it has in it and results from the image version and then we have a new version. In order for a new war to be loaded with this setting, you would need to upload the new war to `/home/noobres/volumes-docker/scadalts/aplicacao/app/`. Then it doesn't matter what version of the base image is, because you decide about the uploaded version by uploading the appropriate version to your location. From what I remember, you needed something like this to freely modify Scada-LTS and for the changes to be visible from the container.

**Comment by odenisnobre** [comment] 2023-10-17 10:04
What version of .war is inside the image?
This is what I need to add to my volume to have the information updated.
Having the same version of .war as in the image, I can add it to:
>/home/noobres/volumes-docker/scadalts/aplicacao/app/

**Comment by Limraj** [comment] 2023-10-17 10:10
first run without:
`- /home/noobres/volumes-docker/scadalts/aplicacao/app/:/usr/local/tomcat/webapps:rw`
and try command:
`docker cp <containerId>:/file/path/within/container /host/path/target`
This command copies a file from the container to the host.

**Comment by odenisnobre** [comment] 2023-10-17 10:43
Perfect, just what I needed.
It worked the way I wanted.
Thank you very much

**Comment by Limraj** [comment] 2023-10-17 11:34
Okay, so I'm closing the topic.

**Closed as completed by Limraj** 2023-10-17 11:34 UTC
Labels: community

**Comment by odenisnobre** [comment] 2023-10-17 12:10
Thank you
